name: drupal-dev
recipe: drupal8
config:
  webroot: drupal
  xdebug: true

services:
  appserver:
    build:
      - echo "Cloning the Drupal project..."
      - git clone http://git.drupal.org/project/drupal.git /app/drupal
      - cd /app/ && COMPOSER_PROCESS_TIMEOUT=600 composer install
